version: '3.9'

services:
  impostor:
    build: .
    container_name: impostor_server
    ports:
      - "127.0.0.1:2025:2025"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    volumes:
      - ./database:/app/database
    restart: unless-stopped
